wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.2
    start_time: 1678787469.59289
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.8.2
      5: 0.13.10
      8:
      - 2
      - 5
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: WhiteELO 2000 arevel
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.01
