version: "3"

services:
  
  fhe_chess:
    container_name: fhe.chess
    image: zamafhe/concrete-ml:1.0.3

    ports:
      - 8888:8888
    
    tty: true
    
    environment:
      DISPLAY: host.docker.internal:0

    volumes:
      - .:/app_src
